In [2]:
import numpy as np
arr = np.array([[4,3,2],[10,2,0],[5,8,24]])
arr

array([[ 4,  3,  2],
       [10,  2,  0],
       [ 5,  8, 24]])

In [5]:
np.amin(arr)

np.int32(0)

In [4]:
np.amin(arr, axis=0)

array([4, 2, 0])

In [6]:
np.amin(arr, axis=1)

array([2, 0, 5])

In [7]:
np.max(arr)

np.int32(24)

In [8]:
np.amax(arr, axis=0)

array([10,  8, 24])

In [9]:
np.amax(arr, axis=1)

array([ 4, 10, 24])

In [10]:
np.median(arr)

np.float64(4.0)

In [11]:
np.mean(arr)

np.float64(6.444444444444445)

In [12]:
np.std(arr)

np.float64(6.865551869233515)

In [13]:
np.var(arr)

np.float64(47.13580246913581)

In [18]:
np.percentile([0, 30, 45, 60, 90], 50)

np.float64(45.0)

In [19]:
deg = 90

np.sin(deg * np.pi / 180)

np.float64(1.0)

In [20]:
np.cos(deg * np.pi / 180)

np.float64(6.123233995736766e-17)

In [21]:
np.tan(deg * np.pi / 180)

np.float64(1.633123935319537e+16)

In [22]:
deg * np.pi / 180

1.5707963267948966

In [28]:
arr = np.array([0, 1, 0, 8, -2.2, -9, 87])

np.floor(arr)

array([ 0.,  1.,  0.,  8., -3., -9., 87.])

In [29]:
np.ceil(arr)

array([ 0.,  1.,  0.,  8., -2., -9., 87.])